CREATE TABLE IF NOT EXISTS `IFFIx_houses` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `owner` VARCHAR(50) DEFAULT NULL,
  `price` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `shell` VARCHAR(50) NOT NULL,
  `position` JSON NOT NULL,
  `interiorCoords` JSON DEFAULT NULL,
  `exitCoords` JSON DEFAULT NULL,
  `storage` JSON DEFAULT NULL,
  `wardrobe` JSON DEFAULT NULL,
  `stash` JSON DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
